### ISSUE TITLE
not working when using cosmic-greeter, works with gdm3

### ISSUE THREAD

**Issue by squalou** [cosmic-utils/clipboard-manager#71]
#### Bug Description

applet is not 'populated' by copy when using cosmic-greetr as login manager.

Works great with gdm3.

#### Expected Result

When copy text, it goes to the applet stack

#### Steps to Reproduce

Ideally using popOS 22.04, install cosmic alpha, run with gdm3 -> it works.

switch to cosmic-greeter, `sudo dpkg-reconfigure cosmic-greeter`, logout, login : applet does not work.

switch again, logout, login, things work again.

**Comment by wiiznokes** [comment]
Interesting. You should report it directly to cosmic-greeter https://github.com/pop-os/cosmic-greeter/issues

**Comment by wiiznokes** [comment]
you shoud try with the latest changes (see #82 )

**Comment by squalou** [comment]
indeed !
thank you
