### ISSUE TITLE
Add an "session unique" toogle

### ISSUE THREAD

**Issue by wiiznokes** [cosmic-utils/clipboard-manager#88]
It will clear the history when the session is finish

**Comment by edfloreshz** [comment]
This is a cool feature.

**Comment by wiiznokes** [comment]
Yeah i saw it while testing pano. I take some inspiration from it

**Comment by wiiznokes** [comment]
this one https://github.com/cosmic-utils/clipboard-manager/issues/20#issuecomment-2383891180 will be hard :smile:
