### ISSUE TITLE
Improve deletion

### ISSUE THREAD

**Issue by Department-stack** [cosmic-utils/clipboard-manager#94]
#### Proposed Change
I think that the deletion of entries could be improved. I think it should be like kde plasma where if you hover over it, a trash can icon shows up, and when pressed deletes the entry. This would be faster than right clicking. Also, you can repeatedly click in the same spot to delete multiple entries. It would also be nice to be able to hold shift to select multiple entries for deletion.

**Comment by wiiznokes** [comment]
> I think it should be like kde plasma where if you hover over it, a trash can icon shows up, and when pressed deletes the entry.

This is not planned. I prefer to not have button on the entry.

> It would also be nice to be able to hold shift to select multiple entries for deletion.

I'm open for PR for that
