### ISSUE TITLE
Nix Packaging Support for cosmic-utils/clipboard-manager

### ISSUE THREAD

**Issue by FelixSchausberger** [cosmic-utils/clipboard-manager#98]
Hi there!

Thank you for creating this project – it looks like a fantastic clipboard management tool!

I was wondering if there are any plans to package cosmic-utils/clipboard-manager for Nix? It would be awesome to see it available in the Nixpkgs repository for NixOS users. I’d be happy to help with testing if needed.

Thanks in advance!

Best,
Felix

**Comment by wiiznokes** [comment]
Hi, I'm not very familiar with nix but there is a flake in this repo https://github.com/lilyinstarlight/nixos-cosmic/
